### PR TITLE
fix 'help test' execution

### LINKED ISSUE #102: workflows "test executable help output" section has some errors
While working on the nodejs updates, noticed that the `test executable help output` section of the workflow is generating a lot of import errors ... it's marking things as passed, so either the test is wrong, or the output is wrong, but "Something's weird here, can you talk a look?"  From poking, I think it's because the dependencies aren't there, but it really looks like they should be ... so we're in "cknowles-moz needs redirection/education" territory

Would love an education if/when any findings occur.

### PR DESCRIPTION
**Pull request by aerickson**
Rewrite 'help test' in python.

The original bash script had issues regarding `find -exec`. `-exec` doesn't check the result code of what's being executed. Piping to xargs is a solution (xargs checks the result code of all commands), but it just felt easier to start over in python.

Fixes #102. Also fixes issue where actions wouldn't run on PRs.

### CODE REVIEW

**Review by cknowles-moz — COMMENTED** [review]
Looks good, just two questions, 1's not a blocker, 2 might be something
1) is there a reason you went for the ASCII art?  Just feeling puckish on a Friday?  It made me smile, so I'm good, just curious if this is some standard practice now... 
2) Poking test items - I made a stub that had no arg handling at all - and so didn't have a --help response.  But it also returned exit code 0.  So this totally tests if "--help" results in an error, but it doesn't actually catch if they don't do --help at all.  (the stub was just a "hello world")

**Comment by aerickson** [comment]
1.) Mostly fun, but it also makes it stand out in the output.
2.) Yeah, we're not guarding for a malicious author... just that all binaries implement a help argument (and we assume it's useful help).

**Comment by cknowles-moz** [comment]
Right, wasn't clear, I'm saying I can make a python script that doesn't implement a --help that passes the test...  Which as I re-read your comments is what you're testing.  "I didn't fall over horribly when you asked me for help."  I guess I'm having trouble understanding the use case for this test.  In my head I've been thinking "you actually give me HELP when I ask" is the thing we're testing for - but that would be hard to do in any real fashion.  

In any case - this harms nothing and does what it says, so I'm OK with it.  Thanks. 

My example - which meets your test but doesn't give help ... which is what I've been thinking is the intended alert of this test.  but on re-reading the comments, totally isn't.  

tmp.py:
```
#!/usr/bin/env python

def main():
    print("HI!")

if __name__ == "__main__":
    main()
```

```
% ./tmp.py --help
HI!
% echo $?
0
```

**Comment by aerickson** [comment]
I can't think of how to check if programs implement a `--help` function vs just not explode when given `--help` (like in your example). It's not a perfect test, but it makes sure that `--help` works (if implemented).

**Comment by cknowles-moz** [comment]
Yup, that's where I am too.  I vote merging this in.  Thank you for bearing with me.

**Pull request merged**
